[package]
name = "merkle-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256="1.4.0"
uint = "0.9.0"
sha2 = "0.10.0"
digest = "0.10.0"